### ISSUE TITLE
regarding to the auxiliary matrices in sparse implementation

### ISSUE THREAD

**Issue by koichishi** [dilevin/computer-graphics-mass-spring-systems#15]
Since the calculations of the auxiliary "d" and "y" in fast_mass_springs_step_sparse.cpp involves normal(dense) matrix, should we just assume these are dense matrices and keep this file the same as fast_mass_springs_step_dense.cpp?

**Comment by abhimadan** [comment]
Try it out and see if it works :)

**Comment by koichishi** [comment]
Thank you. It does work but I am not sure if there is a faster way of doing it...

**Comment by abhimadan** [comment]
If the skirt and flag examples are significantly faster than they would be using your dense code, then you should be fine.
