### ISSUE TITLE
Error on cdf machine

### ISSUE THREAD

**Issue by koichishi** [dilevin/computer-graphics-mass-spring-systems#16]
When I test my code on the graphic interface (NX Client) of CDF, an error shows up.

> **(there goes the function call)** nxsrv:~/(path to the file)/csc418/computer-graphics-mass-spring-systems/out$ ./masssprings_dense ../data/net.json
> VT: 0,0
> FT: 0,0
> masssprings_dense: /(path to the file)/csc418/computer-graphics-mass-spring-systems/libigl/external/eigen/Eigen/src/Core/CwiseBinaryOp.h:132: Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::CwiseBinaryOp(const Lhs&, const Rhs&, const BinaryOp&) [with BinaryOp = Eigen::internal::scalar_sum_op<double>; Lhs = const Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double>, const Eigen::GeneralProduct<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, const Eigen::Transpose<Eigen::Matrix<double, -1, -1> > >, Eigen::Matrix<double, -1, -1>, 5>, const Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, const Eigen::Matrix<double, -1, -1> > >; Rhs = const Eigen::GeneralProduct<Eigen::GeneralProduct<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, const Eigen::Transpose<Eigen::Matrix<double, -1, -1> > >, Eigen::Matrix<double, -1, -1>, 5>, Eigen::Matrix<double, -1, -1>, 5>]: Assertion `aLhs.rows() == aRhs.rows() && aLhs.cols() == aRhs.cols()' failed.

It is really confusing since it seems to tell me that there is a dimension error when doing matrix calculation, which should also be a problem when testing on my own Windows10 VS, but my code works fine in both realese mode and debug mode on my computer.

Can somebody help me with this? Thank you!

**Comment by abhimadan** [comment]
It's hard to tell why this is happening from this error message alone. Attach a debugger to this and find out where this assertion failure is happening in your code. In case you've never used gdb before (and for the benefit of anyone else reading this), you would do something like the following:
```
gdb ./masssprings_dense
// From here to the end are gdb commands, except for lines like this which are comments
r ../data/net.json
bt
// check where this error is happening, either in main.cpp or in your own code
```
One possibility is that your data directory is missing on the server. We don't have any checks on command line arguments so it will crash in an obscure way (we should fix this, but that's for another time).

**Comment by koichishi** [comment]
Thank you for replying.
After a set of random debug processes, it now doesn' have this issue anymore.
However it now shows segmentation faults on the CDF, and my code still works fine on my own Windows10 VS.

Here is the gdb info:

> (gdb) r ../data/single-spring-horizontal.json
> Starting program: /h/u9/c7/00/shigongy/Desktop/csc418/computer-graphics-mass-spring-systems/out/masssprings_dense ../data/single-spring-horizontal.json
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> VT: 0,0
> FT: 0,0
> igl::opengl::glfw::Viewer usage:
>   [drag]  Rotate scene
>   A,a     Toggle animation (tight draw loop)
>   F,f     Toggle face based
>   I,i     Toggle invert normals
>   L,l     Toggle wireframe
>   O,o     Toggle orthographic/perspective projection
>   T,t     Toggle filled faces
>   Z       Snap to canonical view
>   [,]     Toggle between rotation control types (trackball, two-axis
>           valuator with fixed up, 2D mode with no rotation))
>   <,>     Toggle between models
>   ;       Toggle vertex labels
>   :       Toggle face labels
> 
>   [space]  (turn off animation and) step forward one time step
>   A,a  toggle animation 
>   L,l  show/hide edges (springs) and verties (point masses)
>   R,r  reset to rest configuration
>   W,w  toggle horizontal wind
> GLX: GLX version 1.3 is required
> Program received signal SIGSEGV, Segmentation fault.
> 0x0000000000000000 in ?? ()
> (gdb) bt
> #0  0x0000000000000000 in ?? ()
> #1  0x00005555557d92a4 in igl::opengl::MeshGL::init_buffers() ()
> #2  0x00005555557da4b9 in igl::opengl::MeshGL::init() ()
> #3  0x00005555557d3759 in main ()

**Comment by abhimadan** [comment]
Oh, this is because you can't use OpenGL over ssh. The original expectation was that this code would work on the CS teaching lab machines, but since that's not an option anymore, it's fine to just work on it locally.

**Comment by koichishi** [comment]
That's perfect. Thank you!
