### ISSUE TITLE
The skirt on my computer seems more crumpled than the website skirt. Is that skirt.json same as ours? Do we need it to look the same?

### ISSUE THREAD

**Issue by HenryCloud** [dilevin/computer-graphics-mass-spring-systems#18]

**Comment by HenryCloud** [comment]
Mine:
<img width="197" alt="WechatIMG106" src="https://user-images.githubusercontent.com/32419924/79090259-151a8200-7d17-11ea-8248-6e1d76e0da3b.png">
The website:
<img width="222" alt="WechatIMG109" src="https://user-images.githubusercontent.com/32419924/79090289-282d5200-7d17-11ea-95b9-cf8dc8d447ea.png">

**Comment by abhimadan** [comment]
Yes, we used the same file to generate that image. Do your other results look the same as the ones in the readme?
