### ISSUE TITLE
Theoretical Question

### ISSUE THREAD

**Issue by AlekseyPanas** [dilevin/computer-graphics-mass-spring-systems#22]
In the lecture slides and assignment, we very quickly jump from the continuous mechanics model to a discrete approximation for the purposes of generating the simulation. However, I think it would help me to understand a very simple continuous case. I tried to write it out on paper but found myself struggling with even the simplest scenario.

Consider a 1d mass connected to a spring with some stiffness k. You are given its initial position and velocity at t=0. How would I go about computing the continuous function x(t), the position of the mass at any time after t=0. I want to get some x(t)=... expression where I can evaluate the right hand side with the variable t and the provided initial values.

Where I run into problems: ma = -kx allows me to compute acceleration at some instantaneous position point, so it depends on position
`a(t) = -k*x(t) / m`
and the future position 
`x(t) = x(0) + twice_integral(a(t), dt)`
depends on the accelaration. So it seems like there is a circular dependency. Is there no way to arrive at an x(t) then?

**Comment by alfred-mikhael** [comment]
`a(t) = x''(t)` so the equation `a(t) = -kx(t) / m` is a second order ordinary differential equation. Since you are given both the initial position and velocity, you can get a unique solution. The solution would be 
$$A \sin (t \sqrt{\frac{k}{m}}) + B \cos(t \sqrt{\frac{k}{m}}) $$
Where A and B are constants that depend on the initial position and velocity.

**Comment by Zhecheng-Wang** [comment]
^. Circular dependency implies it is a **spatial-temporal** (partial) differential equation. PDE can be solved, sometimes. But numerically (discrete) a lot of PDEs can be approximated.

**Comment by AlekseyPanas** [comment]
Sooooo I need to take MAT244, got it!
