### ISSUE TITLE
Windows runtime problem...

### ISSUE THREAD

**Issue by desmondlzy** [dilevin/computer-graphics-mass-spring-systems#9]
Hi! I noticed #6 and now am working on my windows 10. I cloned the repo (with `--recursive`) and complied, everything looked fine. But when I tried running `massspring_dense`, it gave me an error and I couldn't see any output before the error occurred. The error message is here 
```
Unhandled exception at 0x010047F0 in masssprings_dense.exe: 0xC0000005: Access violation reading location 0x00000000.
```
Now I've implemented the three 'dense' source files and the same error is still there.

I followed the compilation instruction in the first assignments (which I finished on my windows!).....So I am wondering if anyone runs into the same problem or any solution maybe?

Thanks!

**Comment by abhimadan** [comment]
You need to pass a path to a json file in the `data` directory as a command line argument.

**Comment by desmondlzy** [comment]
It's working, thanks!
